spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: pw
    driverClassName: org.h2.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console.enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
